#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Presentation.Api/Presentation.Api.csproj", "Presentation.Api/"]
COPY ["Checkout.com.PaymentGateway/Checkout.com.PaymentGateway.csproj", "Checkout.com.PaymentGateway/"]
COPY ["Checkout.com.PaymentGateway.DTO/Checkout.com.PaymentGateway.DTO.csproj", "Checkout.com.PaymentGateway.DTO/"]
COPY ["Checkout.com.AcquiringBank.Client/Checkout.com.AcquiringBank.Client.csproj", "Checkout.com.AcquiringBank.Client/"]
COPY ["Checkout.com.AcquiringBank/Checkout.com.AcquiringBank.csproj", "Checkout.com.AcquiringBank/"]
COPY ["Checkout.com.Common/Checkout.com.Common.csproj", "Checkout.com.Common/"]
COPY ["Checkout.com.PaymentGateway.Tests/Checkout.com.PaymentGateway.Tests.csproj", "Checkout.com.PaymentGateway.Tests/"]
COPY ["Checkout.com.AcquiringBank.DTO/Checkout.com.AcquiringBank.DTO.csproj", "Checkout.com.AcquiringBank.DTO/"]
COPY ["3rdPartyBank/3rdPartyBank.csproj", "3rdPartyBank/"]
RUN dotnet restore "Presentation.Api/Presentation.Api.csproj"
COPY . .
WORKDIR "/src/Presentation.Api"
RUN dotnet build "Presentation.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Presentation.Api.csproj" -c Release -o /app/publish

FROM build AS tests
WORKDIR "/src/Checkout.com.PaymentGateway.Tests"
CMD ["dotnet", "test", "--logger:trx"]

# run the unit tests
FROM build AS testRunner
WORKDIR "/src/Checkout.com.PaymentGateway.Tests"
RUN dotnet test --logger:trx

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Presentation.Api.dll"]